name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install BMesh
        run: julia --project -e 'using Pkg; Pkg.add(; url="https://github.com/CodeLenz/BMesh.jl.git")'
      - name: Install LMesh
        run: julia --project -e 'using Pkg; Pkg.add(; url="https://github.com/CodeLenz/LMesh.jl.git")'
      - name: Install TMeshes
        run: julia --project -e 'using Pkg; Pkg.add(; url="https://github.com/CodeLenz/TMeshes.jl.git")'  
      - uses: actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
